os:
  editPreset: nvim
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never
  localBranchSortOrder: recency
customCommands:
  - key: "<c-y>"
    context: "files"
    command: "git diff --staged | pbcopy"
